# Generated by Django 4.2.9 on 2024-01-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
