# Generated by Django 4.2.9 on 2024-01-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_cartitem_user_cartitem_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
    ]
